name: bel
channels:
  - conda-forge
  - pytorch
dependencies:
  - pip=21.3.1
  - python=3.8.12
  - pip:
    - setuptools==59.5.0
    - gym==0.21.0
    - mujoco-py==2.0.2.13
    - multidict==6.0.1
    - numpy==1.22.1
    - pandas==1.3.4
    - ray==1.8.0
    - tensorboard==2.7.0
    - torch==1.10.1
    - tqdm==4.62.3
